# Generated by Django 3.1.2 on 2022-05-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20220505_1402'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleTag',
            new_name='Relation',
        ),
    ]
